spring:
  application:
    name: assignment

  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or none / create / create-drop / validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false

  # google smtp 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: rnsdlsfarm1
    password: vuujkwlxnuxsvyxy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org.example.assignment: DEBUG
